# Generated by Django 5.2.6 on 2025-09-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_itemmodel_options_purchasemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
